alternate: # 網站大標題

statics: "/" # 靜態檔案根目錄
assets: "assets"
css: "css"
js: "js"

open_graph:
#twitter_id:
#google_plus:
#fb_admins:
#fb_app_id:

grayMode: false # 全站黑白濾鏡
# 請注意: 本主題的PWA功能只是一個裝載器,需要自備js和manifest
# 圖片可透過https://lp-pwa.gitee.io/pwa-genicon/生成
pwa:
  enable: false # 開啟PWA功能
  serviceworker: sw.js #serviceworker腳本位置,使用以/為基準的絕對路徑
  manifest: manifest.json #manifest位置,使用以/為基準的絕對路徑

# 實驗性特性
experiments:
  debug: false # 使用debug模式啟動
  disableThemeComment: false # 停用主題評論系統(一般用於關閉評論或讓外掛程式接管評論系統)
  usingRelative: false # _image.yml 使用相對路徑
  optimizeLongPosts: false # 優化長文章，這能讓長文章的FPS提升70%-150%並解決假死問題，但存在一些副作用
  # 具體見https://docs.kaitaku.xyz/guide/theme.html#%E9%95%BF%E6%96%87%E7%AB%A0%E4%BC%98%E5%8C%96
  mobileWidth: 820px # 行動版與桌面版導覽列最短切換長度
  # 使用 Cloudflare Rocket 或其他最佳化功能時需開啟下列補丁，否則主體無法渲染
  cloudflarePatch: false
  coverConfig:
    enableCover: true # 是否開啟頭圖
    enablePreload: true #是否開啟預載頭圖
    enableNextGradientCover: false # 使用CSS漸層作為上/下一頁封面
  copyrightLength: 50 # 自訂複製時顯示copyright的長度

homeConfig:
  gradient: false # 使用CSS漸層作為文章封面
  # fixedCover 效能比預設的更好，且開啟時將啟用LCP最佳化和預先載入 TODO
  fixedCover: "" # 主頁cover(為空則使用bing隨機圖片)

# ShokaX 模組化分包引入設置
# 請關閉所有不使用的模組以優化主題 js 體積和效能
modules:
  player: true # 啟用音樂播放器
  fireworks: true # 啟用滑鼠點擊煙火特效
  unlazyHash: false # 啟用unlazy hash預覽圖支持
  visibilityListener: true # 啟用可見度監聽器
  tabs: true # 啟用選項卡擴充支持，如需開啟 summary 功能請一併開啟
  quiz: true # 啟用文章內問題擴充支持
  fancybox: true # 啟用 fancybox 支援（不建議停用）

# 優化效能區
performance:
  # 使用preconnect預先載入的網址(不建議超過三個)
  preConnect:
    - "https://s4.zstatic.net"
    - "https://at.alicdn.com"
  # 使用dns-prefetch預解析的網址
  dnsPrefetch:

playerAPI: "https://api.injahow.cn" # 結尾不帶/,只填入域名
# 如果條件允許,請參考 https://github.com/injahow/meting-api 自建API
# 使用vercel自行部署,請參考: https://github.com/xizeyoupan/Meting-API

icon:
  favicon: "/favicon.ico"
  apple_touch_icon: "/apple-touch-icon.png"

seo:
  bing:
  google:
  yandex:
  baidu:

visitor:
  clarity: false
  baiduAnalytics: false
  googleAnalytics: false

darkmode: true
auto_dark: # 自動亮/暗模式
  enable: true #是否開啟
  start: 20 #開始時間
  end: 7 #結束時間

auto_scroll: false

loader:
  start: true # 進入頁面時顯示載入動畫
  switch: false # 切換頁面時顯示載入動畫

# 使用polyfill.io自動處理瀏覽器相容問題
polyfill:
  enable: false
  features:
  - default
  - fetch

# 顯示的動畫(煙火)
# 參閱 https://github.com/D-Sketon/mouse-firework
fireworks:
  enable: true
  options:
    excludeElements: ["a"]
    particles:
      - shape: circle
        move: ["emit"]
        easing: easeOutExpo
        colors:
          - "rgba(255,182,185,.9)"
          - "rgba(250,227,217,.9)"
          - "rgba(187,222,214,.9)"
          - "rgba(138,198,209,.9)"
        number: 30
        duration: [1200, 1800]
        shapeOptions:
          radius: [16, 32]
      - shape: circle
        move: ["diffuse"]
        easing: easeOutExpo
        colors: ["#fff"]
        number: 1
        duration: [1200, 1800]
        shapeOptions:
          radius: 20
          alpha: 0.5
          lineWidth: 6


font:
  enable: true
  # 從google字體庫載入,如果自訂@font-face請關閉
  loadFromGoogle: true
  # 字體選項:
  # `external`:從google字體庫載入字體.
  # `family: 字體家族名稱,無需引號
  # `size: x.x`. 以`em`為單位. 預設: 1 (16px)

  # 適用於所有在body標籤內的文字.
  global:
    external: false
    family: Noto Serif JP
    size:

  # 大標題字體.
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5

  # 頁面標題字體.
  title:
    external: true
    family: Noto Serif JP
    size: 2.5

  # 標題字體.
  headings:
    external: true
    family: Noto Serif JP
    size:

  # 文章字體.
  posts:
    external: true
    family:

  # 程式碼區塊的字體
  codes:
    external: true
    family: Inconsolata

# //at.alicdn.com/t/c/font_4415496_59g1326wajd.css => 4415496_59g1326wajd
# 自訂iconfont圖示請參閱文件教學課程
iconfont: "4415496_59g1326wajd"

menu:
  home: / || home
  about:
    default: / || user
    aboutsite: /about/  || user
    admiration: /admiration/ || coffee
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  friends: /friends/ || heart

# https://twikoo.js.org
twikoo:
  enable: true
  mode: vercel # vercel或tencent
  envId: "https://comments.lol-icon.app" # twikoo環境ID,vercel填地址
  region:

# https://waline.js.org/
waline:
  enable: false
  serverURL: ""
  lang: "zh-CN"
  locale: {} # https://waline.js.org/guide/features/i18n.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8% A8%80
  emoji: # 表情包
    - https://unpkg.com/@waline/emojis@1.0.1/weibo
    - https://unpkg.com/@waline/emojis@1.0.1/alus
    - https://unpkg.com/@waline/emojis@1.0.1/bilibili
    - https://unpkg.com/@waline/emojis@1.0.1/qq
    - https://unpkg.com/@waline/emojis@1.0.1/tieba
    - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
  meta: # 可以填寫的內容
    - nick
    - mail
    - link
  requiredMeta: # 必須填寫的內容
    - nick
    - mail
  wordLimit: 0 # 字數限制,0為不限制
  pageSize: 10 # 每頁評論條數
  pageview: false # 是否開啟瀏覽量統計,可獨立開啟

summary:
  enable: false
  introduce: "我是基於ChatGPT-turbo-3.5實現的AI助手，在此網站上負責整理和概括文章" # AI自我介紹
  mode: openai # openai/custom
  pricing: "trial" # trial為試用範本(3 RPM); pay為即用即付範本(60 RPM)
  openai:
    remote: "https://api.openai.com"
    apikey: "key"

# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/Yuzuk1Shimotsuki || github || "#191717"
  #gitee: https://gitee.com/yourname || gitee || "#e60026"
  #google: https://plus.google.com/yourname || google
  #twitter: https://twitter.com/yourname || twitter || "#00aff0"
  #zhihu: https://www.zhihu.com/people/yourname || zhihu || "#1e88e5"
  #music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  #weibo: https://weibo.com/yourname || weibo || "#ea716e"
  #about: https://about.me/yourname || address-card || "#3b5998"
  #email: mailto:foo@xxx.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/ || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  instagram: https://instagram.com/goldenlight6628 || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

sidebar:
  # Sidebar Position.
  position: left
  # position: right
  # Replace the default avatar image under <root>/source/_data/assets/ and set the url here.
  avatar: avatar.webp

widgets:
  # if true, will show random posts
  random_posts: true
  # if true, will show recent comments
  recent_comments: true

footer:
  # Specify the date when the site was set up. If not defined, current year will be used.
  since: 2023
  icon:
    name: sakura rotate
    # Change the color of icon, using Hex Code.
    color: "#ffc0cb"
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true
  powered: true
  lantern:
    enable: true # 是否開啟
    word1: 中 #第一個字
    word2: 秋 #第二個字
  icp: # ICP備案 (僅適用於中國大陸地區)
    enable: false
    # 請在登入後從 https://beian.mps.gov.cn/web/business/businessHome/website 下載答案圖標
    icon: "" #網安備案圖片
    icpnumber: "xxx" # ICP備案號
    beian: "xxx" #網安備案號
    recordcode: "xxx" # 網安備案連結中的recordcode參數

post:
  count: true

# 文章是否失效
outime:
  enable: false
  days: 90 # 超過 90 天文章失效

reward:
  # If true, reward will be displayed in every article by default.
  enable: true
  account:
    wechatpay: /wechatpay.png
    alipay: /alipay.png
    # paypal: /paypal.png

# TagCloud settings for tags page.
tagcloud:
  # All values below are same as default, change them by yourself.
  min: 16 # Minimun font size in px
  max: 22 # Maxium font size in px
  start: "#72cecf" # Start color (hex, rgba, hsla or color keywords)
  end: "#ffbac3" # End color (hex, rgba, hsla or color keywords)
  amount: 200 # Amount of tags, change it if you have more than 200 tags

# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

# Creative Commons 4.0 International License.
# See: https://creativecommons.org/share-your-work/licensing-types-examples
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
# CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
creative_commons:
  license: by-nc-sa
  language: deed.zh

# bgm
# 不使用請開啟noplayer功能
audio:
#  - title: 清單1
#    list:
#      - https://music.163.com/#/playlist?id=2943811283
#      - https://music.163.com/#/playlist?id=2297706586
#  - title: 清單2
#    list:
#      - https://music.163.com/#/playlist?id=2031842656

# random image api
image_server: # "https://acg.xydwz.cn/api/api.php"

# Algolia Search
# For more information: https://www.algolia.com
search:
  hits:
    per_page: 10

# Dependencies: https://github.com/amehime/hexo-renderer-multi-markdown-it
pangu: false

# Quicklink Support
# For more information: https://github.com/GoogleChromeLabs/quicklink
quicklink:
  # Custom a time in milliseconds by which the browser must execute prefetching.
  timeout: 3000
  # Default (true) will attempt to use the fetch() API if supported (rather than link[rel=prefetch]).
  priority: true

  # For more flexibility you can add some patterns (RegExp, Function, or Array) to ignores.
  # See: https://github.com/GoogleChromeLabs/quicklink#custom-ignore-patterns
  ignores:

#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING `vendors` SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------
vendors:
  cdns:
    cdnjs: https://s4.zstatic.net/ajax/libs
  js:
    pace:
      source: cdnjs
      url: pace/1.2.4/pace.min.js
      sri: "sha384-k6YtvFUEIuEFBdrLKJ3YAUbBki333tj1CSUisai5Cswsg9wcLNaPzsTHDswp4Az8"
    jquery:
      source: cdnjs
      url: jquery/3.5.1/jquery.min.js
      sri: "sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2"
  async_js:
    fancybox:
      source: cdnjs
      url: fancybox/3.5.7/jquery.fancybox.min.js
      sri: "sha384-Zm+UU4tdcfAm29vg+MTbfu//q5B/lInMbMCr4T8c9rQFyOv6PlfQYpB5wItcXWe7"
    justifiedGallery:
      source: cdnjs
      url: justifiedGallery/3.8.1/js/jquery.justifiedGallery.min.js
      sri: "sha384-TOxsBplaL96/QDWPIUg+ye3v89qSE3s22XNtJMmCeZEep3cVDmXy1zEfZvVv+y2m"
    copy_tex:
      source: cdnjs
      url: KaTeX/0.16.9/contrib/copy-tex.min.js
      sri: "sha384-ww/583aHhxWkz5DEVn6OKtNiIaLi2iBRNZXfJRiY1Ai7tnJ9UXpEsyvOITVpTl4A"
  css:
    katex:
      source: cdnjs
      url: KaTeX/0.16.9/katex.min.css
      sri: "sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV"
    comment:
      source: local
      url: css/comment.css
      sri: ""
    fancybox:
      source: cdnjs
      url: fancybox/3.5.7/jquery.fancybox.min.css
      sri: "sha384-Q8BgkilbsFGYNNiDqJm69hvDS7NCJWOodvfK/cwTyQD4VQA0qKzuPpvqNER1UC0F"
    justifiedGallery:
      source: cdnjs
      url: justifiedGallery/3.8.1/css/justifiedGallery.min.css
      sri: "sha384-V/1Ew9pYm8xpy/L9i078ZXT6HSEOrGC6KNFYLbXOdtqb3+c6brpGqVzZtEPSQOiz"
